Parameters:

  App:
    Type: String
    Description: Name of Application for identification.
    AllowedPattern: '[A-Za-z0-9]{2,15}'
    ConstraintDescription: App may only contain uppercase or lowercase letters and numbers and must be betweeen 2 and 15 characters

  Vpc:
    Type: String
    Description: Vpc id.
  
  PublicSubnet1:
    Type: String
    Description: Public Subnet1 id.

Resources:
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Web Server Traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0

      VpcId: !Ref Vpc

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e54eba7c51c234f6
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "web-server-${App}"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd.x86_64
          systemctl start httpd.service
          systemctl enable httpd.service
          iptables -A INPUT -p tcp --dport 80 -j ACCEPT
          echo "<html><body><h1>Hello SolvD!<h1></body></html>" > /var/www/html/index.html